#!/usr/bin/env node
/**
 * Build a self-contained static dashboard HTML that embeds benchmark data.
 *
 * Usage:
 *   node tests/build_static_dashboard.mjs
 *   node tests/build_static_dashboard.mjs --out dist/index.html
 *
 * Reads:
 *   - tmp/meljs-variant-benchmark-manifest.json (and all referenced reports)
 *   - tests/benchmark_variants_comparison.html
 *
 * Writes:
 *   - dist/index.html (self-contained, no server needed)
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const MANIFEST_PATH = resolve(ROOT, "tmp/meljs-variant-benchmark-manifest.json");
const TEMPLATE_PATH = resolve(ROOT, "tests/benchmark_variants_comparison.html");
const DEFAULT_OUT = resolve(ROOT, "dist/index.html");

function parseArgs(argv) {
    let out = DEFAULT_OUT;
    for (let i = 0; i < argv.length; i++) {
        if (argv[i] === "--out" && argv[i + 1]) out = resolve(argv[++i]);
    }
    return { out };
}

function main() {
    const args = parseArgs(process.argv.slice(2));

    // 1. Load manifest and all reports
    if (!existsSync(MANIFEST_PATH)) {
        console.error(`Manifest not found: ${MANIFEST_PATH}`);
        console.error("Run 'npm run bench:variants' first to generate benchmark data.");
        process.exit(1);
    }

    const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
    const reports = [];

    for (const entry of manifest.reports || []) {
        const reportPath = resolve(ROOT, "tmp", entry.path);
        if (existsSync(reportPath)) {
            try {
                reports.push(JSON.parse(readFileSync(reportPath, "utf8")));
                console.log(`  Loaded: ${entry.path}`);
            } catch (e) {
                console.warn(`  Skipped (parse error): ${entry.path}`);
            }
        } else {
            console.warn(`  Skipped (not found): ${entry.path}`);
        }
    }

    if (!reports.length) {
        console.error("No valid reports found. Run benchmarks first.");
        process.exit(1);
    }

    console.log(`Loaded ${reports.length} report(s) from manifest.`);

    // 2. Read template HTML
    let html = readFileSync(TEMPLATE_PATH, "utf8");

    // 3. Build the embedded data script
    const embeddedScript = `
<script>
  // ── Embedded benchmark data (generated by build_static_dashboard.mjs) ──
  window.__EMBEDDED_BENCHMARK_DATA__ = ${JSON.stringify(reports)};
  window.__EMBEDDED_MANIFEST__ = ${JSON.stringify(manifest)};
</script>`;

    // 4. Inject embedded data in <head> so it's available before page scripts run
    html = html.replace("</head>", `${embeddedScript}\n</head>`);

    // 5. Replace the auto-load call at the bottom of the page script
    // The original has: loadManifest(); at the end of the <script> block
    // We replace it to use embedded data directly
    html = html.replace(
        "loadManifest();",
        `// Auto-load from embedded data (static build)
    if (window.__EMBEDDED_BENCHMARK_DATA__) {
      state.manifestEntries = window.__EMBEDDED_MANIFEST__.reports || [];
      renderFileList();
      for (let i = 0; i < state.manifestEntries.length; i++) {
        state.activeFileIndices.add(i);
      }
      setReports(window.__EMBEDDED_BENCHMARK_DATA__);
      renderFileList();
    } else {
      loadManifest();
    }`
    );

    // 6. Add a banner indicating this is a static build
    const buildTime = new Date().toISOString();
    const bannerScript = `
<script>
  // Add static build indicator
  const metaEl = document.getElementById("metaText");
  if (metaEl) {
    const origText = metaEl.textContent;
    metaEl.title = "Static build: ${buildTime}";
  }
</script>`;

    html = html.replace("</body>", `${bannerScript}\n</body>`);

    // 7. Write output
    mkdirSync(dirname(args.out), { recursive: true });
    writeFileSync(args.out, html, "utf8");

    const sizeKB = (Buffer.byteLength(html, "utf8") / 1024).toFixed(1);
    console.log(`\nStatic dashboard written: ${args.out} (${sizeKB} KB)`);
    console.log(`Open directly in browser — no server needed.`);
}

main();
